/// End-to-end tests that generate real Terraform files and validate them
/// using actual terraform CLI commands (validate, init without backend)
///
/// These tests ensure that the Terraform code we generate is actually valid
/// and can be used with real Terraform, not just our mocks.

use envie::common::*;
use std::path::PathBuf;
use std::process::Command;
use tempfile::TempDir;

/// Check if terraform is available on the system
fn terraform_available() -> bool {
    Command::new("terraform")
        .arg("version")
        .output()
        .map(|output| output.status.success())
        .unwrap_or(false)
}

/// Helper to create a test workspace configuration
fn create_test_workspace(dir: &TempDir) -> PathBuf {
    let workspace_path = dir.path().join("workspace.envie.yaml");
    let content = r#"
version: '1.0'

project:
  name: test-project

environments:
  ephemeral:
    naming_pattern: "{project}-{id}"
    backend:
      type: s3
      config:
        bucket: "test-bucket"
        region: "us-east-1"
        key_pattern: "ephemeral/{workspace}/{path}/terraform.tfstate"
        dynamodb_table: "test-locks"
        encrypt: "true"

  stable:
    sandbox:
      workspace: test-sandbox
      backend:
        type: s3
        config:
          bucket: "test-bucket"
          region: "us-east-1"
          key_pattern: "stable/sandbox/{path}/terraform.tfstate"
          dynamodb_table: "test-locks"
          encrypt: "true"
"#;
    std::fs::write(&workspace_path, content).unwrap();
    workspace_path
}

/// Helper to create a minimal unit with Terraform files
fn create_unit_with_terraform(
    dir: &TempDir,
    name: &str,
    dependencies: Vec<&str>,
) -> PathBuf {
    let unit_dir = dir.path().join("units").join(name);
    std::fs::create_dir_all(&unit_dir).unwrap();

    // Create envie.yaml
    let mut depends_vec = Vec::new();
    for dep_path in dependencies {
        depends_vec.push(format!("  - path: {}", dep_path));
    }
    let depends_str = if depends_vec.is_empty() {
        "dependencies: []".to_string()
    } else {
        format!("dependencies:\n{}", depends_vec.join("\n"))
    };

    let envie_config = format!(
        r#"name: {}
description: {} infrastructure
unit_type: service
state_management: dedicated
{}
"#,
        name, name, depends_str
    );
    std::fs::write(unit_dir.join("envie.yaml"), envie_config).unwrap();

    // Create a minimal main.tf that will pass validation
    let main_tf = format!(
        r#"# Generated by Envie for unit: {}
terraform {{
  required_version = ">= 1.0"

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

variable "envie_workspace" {{
  description = "Current Envie workspace"
  type        = string
}}

variable "envie_backend_bucket" {{
  description = "Backend S3 bucket"
  type        = string
  default     = ""
}}

variable "envie_backend_region" {{
  description = "Backend region"
  type        = string
  default     = "us-east-1"
}}

variable "envie_backend_dynamodb_table" {{
  description = "Backend DynamoDB table"
  type        = string
  default     = ""
}}

variable "envie_backend_encrypt" {{
  description = "Backend encryption"
  type        = string
  default     = "true"
}}

# Minimal resource for testing
resource "null_resource" "{}" {{
  triggers = {{
    workspace = var.envie_workspace
  }}
}}

output "unit_name" {{
  description = "Name of this unit"
  value       = "{}"
}}

output "workspace" {{
  description = "Current workspace"
  value       = var.envie_workspace
}}
"#,
        name, name, name
    );
    std::fs::write(unit_dir.join("main.tf"), main_tf).unwrap();

    unit_dir
}

/// Run terraform validate on a directory
fn run_terraform_validate(dir: &PathBuf) -> Result<String> {
    let output = Command::new("terraform")
        .arg("validate")
        .arg("-json")
        .current_dir(dir)
        .output()
        .map_err(|e| EnvieError::ProcessError(format!("Failed to run terraform validate: {}", e)))?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(EnvieError::ProcessError(format!(
            "Terraform validation failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )))
    }
}

/// Run terraform init without backend
fn run_terraform_init_no_backend(dir: &PathBuf) -> Result<String> {
    let output = Command::new("terraform")
        .arg("init")
        .arg("-backend=false")
        .current_dir(dir)
        .output()
        .map_err(|e| EnvieError::ProcessError(format!("Failed to run terraform init: {}", e)))?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    } else {
        Err(EnvieError::ProcessError(format!(
            "Terraform init failed:\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )))
    }
}

#[test]
fn test_simple_unit_terraform_validation() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);
    let unit_dir = create_unit_with_terraform(&temp_dir, "api", vec![]);

    // Initialize terraform (download providers)
    let init_result = run_terraform_init_no_backend(&unit_dir);
    assert!(
        init_result.is_ok(),
        "Terraform init should succeed: {:?}",
        init_result
    );

    // Validate the generated Terraform
    let validate_result = run_terraform_validate(&unit_dir);
    assert!(
        validate_result.is_ok(),
        "Generated Terraform should be valid: {:?}",
        validate_result
    );

    // Parse validation output
    let validation_output = validate_result.unwrap();
    assert!(
        validation_output.contains("\"valid\": true") || validation_output.contains("Success"),
        "Validation should report success"
    );
}

#[test]
fn test_unit_with_variables_terraform_validation() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);

    // Create a unit with custom variables
    let unit_dir = temp_dir.path().join("units/database");
    std::fs::create_dir_all(&unit_dir).unwrap();

    let envie_config = r#"name: database
description: Database infrastructure
unit_type: service
state_management: dedicated
dependencies: []
"#;
    std::fs::write(unit_dir.join("envie.yaml"), envie_config).unwrap();

    let main_tf = r#"terraform {
  required_version = ">= 1.0"
}

variable "envie_workspace" {
  type = string
}

variable "db_instance_class" {
  description = "Database instance class"
  type        = string
  default     = "db.t3.micro"
}

variable "db_name" {
  description = "Database name"
  type        = string
  default     = "myapp"
}

output "endpoint" {
  value = "mock-endpoint.${var.envie_workspace}.rds.amazonaws.com"
}
"#;
    std::fs::write(unit_dir.join("main.tf"), main_tf).unwrap();

    // Initialize and validate
    let init_result = run_terraform_init_no_backend(&unit_dir);
    assert!(init_result.is_ok(), "Init should succeed");

    let validate_result = run_terraform_validate(&unit_dir);
    assert!(
        validate_result.is_ok(),
        "Validation should succeed: {:?}",
        validate_result
    );
}

#[test]
fn test_linear_dependency_chain() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);

    // Create chain: api -> database -> networking
    let networking_dir = create_unit_with_terraform(&temp_dir, "networking", vec![]);
    let database_dir = create_unit_with_terraform(&temp_dir, "database", vec!["../networking"]);
    let api_dir = create_unit_with_terraform(&temp_dir, "api", vec!["../database"]);

    // Validate each unit in dependency order
    for (name, dir) in &[
        ("networking", &networking_dir),
        ("database", &database_dir),
        ("api", &api_dir),
    ] {
        let init_result = run_terraform_init_no_backend(dir);
        assert!(
            init_result.is_ok(),
            "Init should succeed for {}: {:?}",
            name,
            init_result
        );

        let validate_result = run_terraform_validate(dir);
        assert!(
            validate_result.is_ok(),
            "Validation should succeed for {}: {:?}",
            name,
            validate_result
        );
    }
}

#[test]
fn test_diamond_dependency_pattern() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);

    // Create diamond: api -> (database, cache) -> networking
    //     api
    //    /   \
    //  db   cache
    //    \   /
    //   network
    let networking_dir = create_unit_with_terraform(&temp_dir, "networking", vec![]);
    let database_dir = create_unit_with_terraform(&temp_dir, "database", vec!["../networking"]);
    let cache_dir = create_unit_with_terraform(&temp_dir, "cache", vec!["../networking"]);
    let api_dir = create_unit_with_terraform(&temp_dir, "api", vec!["../database", "../cache"]);

    // Validate each unit
    for (name, dir) in &[
        ("networking", &networking_dir),
        ("database", &database_dir),
        ("cache", &cache_dir),
        ("api", &api_dir),
    ] {
        let init_result = run_terraform_init_no_backend(dir);
        assert!(
            init_result.is_ok(),
            "Init should succeed for {}: {:?}",
            name,
            init_result
        );

        let validate_result = run_terraform_validate(dir);
        assert!(
            validate_result.is_ok(),
            "Validation should succeed for {}: {:?}",
            name,
            validate_result
        );
    }
}

#[test]
fn test_complex_microservices_architecture() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);

    // Create complex architecture:
    // - VPC (base)
    // - Database depends on VPC
    // - Cache depends on VPC
    // - Auth service depends on Database
    // - User service depends on Database and Cache
    // - API Gateway depends on Auth and User services

    let vpc_dir = create_unit_with_terraform(&temp_dir, "vpc", vec![]);
    let database_dir = create_unit_with_terraform(&temp_dir, "database", vec!["../vpc"]);
    let cache_dir = create_unit_with_terraform(&temp_dir, "cache", vec!["../vpc"]);
    let auth_dir = create_unit_with_terraform(&temp_dir, "auth", vec!["../database"]);
    let user_dir =
        create_unit_with_terraform(&temp_dir, "user", vec!["../database", "../cache"]);
    let api_gateway_dir =
        create_unit_with_terraform(&temp_dir, "api_gateway", vec!["../auth", "../user"]);

    let units = vec![
        ("vpc", &vpc_dir),
        ("database", &database_dir),
        ("cache", &cache_dir),
        ("auth", &auth_dir),
        ("user", &user_dir),
        ("api_gateway", &api_gateway_dir),
    ];

    // Validate all units
    for (name, dir) in &units {
        let init_result = run_terraform_init_no_backend(dir);
        assert!(
            init_result.is_ok(),
            "Init should succeed for {}: {:?}",
            name,
            init_result
        );

        let validate_result = run_terraform_validate(dir);
        assert!(
            validate_result.is_ok(),
            "Validation should succeed for {}: {:?}",
            name,
            validate_result
        );
    }
}

#[test]
fn test_unit_with_remote_state_data_sources() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    create_test_workspace(&temp_dir);

    // Create database unit
    let database_dir = temp_dir.path().join("units/database");
    std::fs::create_dir_all(&database_dir).unwrap();

    let db_config = r#"name: database
description: Database
unit_type: service
state_management: dedicated
dependencies: []
"#;
    std::fs::write(database_dir.join("envie.yaml"), db_config).unwrap();

    let db_main = r#"terraform {
  required_version = ">= 1.0"
}

variable "envie_workspace" {
  type = string
}

output "endpoint" {
  value = "db.${var.envie_workspace}.example.com"
}

output "port" {
  value = 5432
}
"#;
    std::fs::write(database_dir.join("main.tf"), db_main).unwrap();

    // Create API unit that references database outputs
    let api_dir = temp_dir.path().join("units/api");
    std::fs::create_dir_all(&api_dir).unwrap();

    let api_config = r#"name: api
description: API
unit_type: service
state_management: dedicated
dependencies:
  - path: ../database
"#;
    std::fs::write(api_dir.join("envie.yaml"), api_config).unwrap();

    // Create main.tf with data source for remote state
    let api_main = r#"terraform {
  required_version = ">= 1.0"
}

variable "envie_workspace" {
  type = string
}

variable "envie_backend_bucket" {
  type    = string
  default = ""
}

variable "envie_backend_region" {
  type    = string
  default = "us-east-1"
}

# This would reference the database's remote state
# For now, using locals to simulate
locals {
  database_endpoint = "mock-db.${var.envie_workspace}.example.com"
  database_port     = 5432
}

output "database_connection" {
  value = "${local.database_endpoint}:${local.database_port}"
}
"#;
    std::fs::write(api_dir.join("main.tf"), api_main).unwrap();

    // Validate both units
    for (name, dir) in &[("database", &database_dir), ("api", &api_dir)] {
        let init_result = run_terraform_init_no_backend(dir);
        assert!(
            init_result.is_ok(),
            "Init should succeed for {}: {:?}",
            name,
            init_result
        );

        let validate_result = run_terraform_validate(dir);
        assert!(
            validate_result.is_ok(),
            "Validation should succeed for {}: {:?}",
            name,
            validate_result
        );
    }
}

#[test]
fn test_unit_with_provider_configuration() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    let unit_dir = temp_dir.path().join("units/multi_region");
    std::fs::create_dir_all(&unit_dir).unwrap();

    let config = r#"name: multi_region
description: Multi-region setup
unit_type: service
state_management: dedicated
dependencies: []
"#;
    std::fs::write(unit_dir.join("envie.yaml"), config).unwrap();

    // Create Terraform with multiple provider configurations
    let main_tf = r#"terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

variable "envie_workspace" {
  type = string
}

provider "aws" {
  region = "us-east-1"

  # Skip credentials for validation
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
}

provider "aws" {
  alias  = "west"
  region = "us-west-2"

  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
}

output "primary_region" {
  value = "us-east-1"
}

output "secondary_region" {
  value = "us-west-2"
}
"#;
    std::fs::write(unit_dir.join("main.tf"), main_tf).unwrap();

    let init_result = run_terraform_init_no_backend(&unit_dir);
    assert!(init_result.is_ok(), "Init should succeed: {:?}", init_result);

    let validate_result = run_terraform_validate(&unit_dir);
    assert!(
        validate_result.is_ok(),
        "Validation should succeed: {:?}",
        validate_result
    );
}

#[test]
fn test_invalid_terraform_syntax_detection() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    let unit_dir = temp_dir.path().join("units/invalid");
    std::fs::create_dir_all(&unit_dir).unwrap();

    // Create intentionally invalid Terraform
    let invalid_tf = r#"terraform {
  required_version = ">= 1.0"
}

# Invalid syntax - missing closing brace
variable "test" {
  type = string

output "test" {
  value = "test"
}
"#;
    std::fs::write(unit_dir.join("main.tf"), invalid_tf).unwrap();

    // Validation should fail
    let validate_result = run_terraform_validate(&unit_dir);
    assert!(
        validate_result.is_err(),
        "Validation should fail for invalid syntax"
    );
}

#[test]
fn test_missing_required_variable() {
    if !terraform_available() {
        eprintln!("Skipping test: terraform not available");
        return;
    }

    let temp_dir = TempDir::new().unwrap();
    let unit_dir = temp_dir.path().join("units/test");
    std::fs::create_dir_all(&unit_dir).unwrap();

    // Create Terraform that references undefined variable
    let main_tf = r#"terraform {
  required_version = ">= 1.0"
}

variable "defined_var" {
  type = string
}

# This references an undefined variable
output "test" {
  value = var.undefined_var
}
"#;
    std::fs::write(unit_dir.join("main.tf"), main_tf).unwrap();

    let init_result = run_terraform_init_no_backend(&unit_dir);
    assert!(init_result.is_ok(), "Init should succeed");

    // Validation should fail due to undefined variable
    let validate_result = run_terraform_validate(&unit_dir);
    assert!(
        validate_result.is_err(),
        "Validation should fail for undefined variable"
    );
}
