# Auto-generated by Envie - DO NOT EDIT
# This file is automatically generated and will be overwritten

project_name = "full-demo"
environment_id = "e2e-test"
module_name = "vpc"

# Common tags
tags = {
  Project     = "full-demo"
  Environment = "e2e-test"
  Module      = "vpc"
  ManagedBy   = "envie"
}
