# Backend configuration generated by Envie
# State management: Dedicated
# State key: ephemeral/full-demo-e2e-test/lambda/lambda/terraform.tfstate

terraform {
  backend "s3" {
    region = "us-east-1"
    bucket = "full-demo-terraform-state-20250108"
    key = "ephemeral/full-demo-e2e-test/lambda/lambda/terraform.tfstate"
    encrypt = "true"
    dynamodb_table = "full-demo-terraform-locks"

  }
}
