name: lambda
description: Lambda function for the full demo app
unit_type: component
state_management: dedicated

depends:
  - path: ../../networking/vpc
    environment: ephemeral
  - path: ../../database/dynamodb
    environment: ephemeral
