# Subnets Module - Lightweight Version
# Uses null resources for fast deployment

# Data source for VPC
data "terraform_remote_state" "vpc" {
  backend = "s3"
  # This will be auto-generated by Envie
}

variable "availability_zones" {
  description = "List of availability zones"
  type        = list(string)
  default     = ["eu-west-1a", "eu-west-1b"]
}

# Simulate Public Subnets
resource "null_resource" "public_subnets" {
  count = length(var.availability_zones)

  depends_on = [data.terraform_remote_state.vpc]

  triggers = {
    vpc_id = data.terraform_remote_state.vpc.outputs.vpc_id
    az     = var.availability_zones[count.index]
  }

  provisioner "local-exec" {
    command = "echo 'Public subnet created in ${var.availability_zones[count.index]}'"
  }
}

# Simulate Private Subnets
resource "null_resource" "private_subnets" {
  count = length(var.availability_zones)

  depends_on = [data.terraform_remote_state.vpc]

  triggers = {
    vpc_id = data.terraform_remote_state.vpc.outputs.vpc_id
    az     = var.availability_zones[count.index]
  }

  provisioner "local-exec" {
    command = "echo 'Private subnet created in ${var.availability_zones[count.index]}'"
  }
}

# Outputs
output "public_subnet_ids" {
  description = "IDs of the public subnets"
  value       = [for i in range(length(var.availability_zones)) : "subnet-public-${i}"]
}

output "private_subnet_ids" {
  description = "IDs of the private subnets"
  value       = [for i in range(length(var.availability_zones)) : "subnet-private-${i}"]
}

output "public_subnets" {
  description = "Public subnets"
  value       = [for i in range(length(var.availability_zones)) : {
    id = "subnet-public-${i}"
    az = var.availability_zones[i]
  }]
}

output "private_subnets" {
  description = "Private subnets"
  value       = [for i in range(length(var.availability_zones)) : {
    id = "subnet-private-${i}"
    az = var.availability_zones[i]
  }]
}