# Step Functions Module - Lightweight Version
# Uses Step Functions for workflow orchestration

# Data source for Lambda
data "terraform_remote_state" "api_lambda" {
  backend = "s3"
  # This will be auto-generated by Envie
}

variable "state_machine_name" {
  description = "Name of the Step Functions state machine"
  type        = string
  default     = "example-workflow"
}

# Step Functions state machine
resource "aws_sfn_state_machine" "workflow" {
  name     = "${var.state_machine_name}-${random_id.sf_id.hex}"
  role_arn = aws_iam_role.step_functions_role.arn

  definition = jsonencode({
    Comment = "Example workflow"
    StartAt = "ProcessRequest"
    States = {
      ProcessRequest = {
        Type     = "Task"
        Resource = data.terraform_remote_state.api_lambda.outputs.function_arn
        Next     = "Success"
      }
      Success = {
        Type = "Succeed"
      }
    }
  })

  tags = {
    Name        = "example-workflow"
    Environment = "ephemeral"
    Service     = "api"
    Module      = "step-functions"
  }
}

# Random ID for uniqueness
resource "random_id" "sf_id" {
  byte_length = 4
}

# IAM role for Step Functions
resource "aws_iam_role" "step_functions_role" {
  name = "step-functions-role-${random_id.sf_id.hex}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "states.amazonaws.com"
        }
      }
    ]
  })
}

# Policy to invoke Lambda
resource "aws_iam_role_policy" "step_functions_lambda" {
  name = "step-functions-lambda-${random_id.sf_id.hex}"
  role = aws_iam_role.step_functions_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "lambda:InvokeFunction"
        ]
        Resource = data.terraform_remote_state.api_lambda.outputs.function_arn
      }
    ]
  })
}

# Outputs
output "state_machine_arn" {
  description = "ARN of the Step Functions state machine"
  value       = aws_sfn_state_machine.workflow.arn
}

output "state_machine_name" {
  description = "Name of the Step Functions state machine"
  value       = aws_sfn_state_machine.workflow.name
}
