use crate::common::*;
use std::collections::HashMap;
use std::path::Path;

#[derive(Debug, Clone)]
pub struct TerraformGenerator {
    pub backend_config: BackendConfig,
}

#[derive(Debug, Clone)]
pub struct BackendConfig {
    pub backend_type: String,
    pub config: HashMap<String, String>,
}

impl Default for BackendConfig {
    fn default() -> Self {
        let mut config = HashMap::new();
        config.insert("bucket".to_string(), "terraform-state-bucket".to_string());
        config.insert("region".to_string(), "eu-west-1".to_string());
        config.insert("key".to_string(), "terraform.tfstate".to_string());
        
        Self {
            backend_type: "s3".to_string(),
            config,
        }
    }
}

impl TerraformGenerator {
    pub fn new() -> Self {
        Self {
            backend_config: BackendConfig::default(),
        }
    }
    
    pub fn with_backend(mut self, backend: BackendConfig) -> Self {
        self.backend_config = backend;
        self
    }
    
    pub fn generate_remote_state_data_sources(
        &self,
        module_path: &Path,
        dependencies: &[crate::common::service_config::DependencyReference],
        environment_resolver: &EnvironmentResolver,
        environment_overrides: &std::collections::HashMap<String, String>,
        service_name: &str,
        _module_name: &str,
    ) -> Result<String> {
        let mut generated = String::new();
        
        generated.push_str("# Auto-generated by Envie - DO NOT EDIT\n");
        generated.push_str("# This file is automatically generated and will be overwritten\n\n");
        
        // First, scan existing Terraform files to see what data sources are already used
        let scanner = TerraformScanner::new()?;
        let existing_deps = scanner.scan_directory(module_path)?;
        
        // Create a set of existing data source names to avoid duplicates
        let existing_names: std::collections::HashSet<String> = existing_deps
            .iter()
            .map(|dep| dep.data_source_name.clone())
            .collect();
        
        for dependency in dependencies {
            // Check for CLI override for this dependency
            let (source_service, source_module) = self.extract_service_module_from_source(&dependency.path)?;
            let environment_to_use = if let Some(override_env) = environment_overrides.get(&source_service) {
                override_env.clone()
            } else {
                dependency.environment.clone()
            };
            
            let resolved_env = environment_resolver.resolve_environment(&environment_to_use)?;
            
            // Generate a more descriptive name: service_module
            let data_source_name = if source_service == "current" {
                format!("{}_{}", service_name, source_module)
            } else {
                format!("{}_{}", source_service, source_module)
            };
            
            // Skip if this data source already exists
            if existing_names.contains(&data_source_name) {
                continue;
            }
            
            generated.push_str(&format!(
                r#"data "terraform_remote_state" "{}" {{
  backend = "{}"
  workspace = "{}"
  
  config = {{
"#,
                data_source_name,
                resolved_env.backend.backend_type,
                resolved_env.workspace
            ));
            
            let state_key = environment_resolver.generate_state_key(&resolved_env, &source_service, &source_module);
            for (key, value) in &resolved_env.backend.config {
                if key == "key_pattern" {
                    generated.push_str(&format!("    key = \"{}\"\n", state_key));
                } else {
                    generated.push_str(&format!("    {} = \"{}\"\n", key, value));
                }
            }
            
            generated.push_str("  }\n}\n\n");
        }
        
        Ok(generated)
    }
    
    fn extract_service_module_from_source(&self, source: &str) -> Result<(String, String)> {
        // Convert source path to service/module
        // e.g., "../database/modules/dynamodb" -> ("database", "dynamodb")
        // e.g., "./lambda" -> (current_service, "lambda")
        // e.g., "../../database/modules/dynamodb" -> ("database", "dynamodb")
        
        let normalized_source = source
            .replace("../", "")
            .replace("./", "")
            .replace("//", "/");
        
        let parts: Vec<&str> = normalized_source.split('/').collect();
        
        if parts.len() >= 2 {
            let service = parts[0].to_string();
            let module = parts[parts.len() - 1].to_string();
            Ok((service, module))
        } else if parts.len() == 1 {
            // Local module reference
            Ok(("current".to_string(), parts[0].to_string()))
        } else {
            Err(EnvieError::ValidationError(
                format!("Invalid source path: {}", source)
            ))
        }
    }
    
    fn generate_state_key(&self, source: &str, _workspace: &str) -> Result<String> {
        // Convert source path to state key
        // e.g., "../database/modules/dynamodb" -> "database/dynamodb/terraform.tfstate"
        let normalized_source = source
            .replace("../", "")
            .replace("./", "")
            .replace("//", "/");
        
        Ok(format!("{}/terraform.tfstate", normalized_source))
    }
    
    pub fn generate_backend_configuration(
        &self,
        module_config: &ModuleConfig,
        environment_resolver: &EnvironmentResolver,
        service_name: &str,
        module_name: &str,
    ) -> Result<String> {
        // Determine the environment to use (for now, use ephemeral as default)
        let environment = "ephemeral";
        let resolved_env = environment_resolver.resolve_environment(environment)?;
        
        // Generate state key based on state management strategy
        let state_key = match &module_config.state_management {
            crate::common::service_config::StateManagement::Dedicated => {
                // Module gets its own state file
                environment_resolver.generate_state_key(&resolved_env, service_name, module_name)
            }
            crate::common::service_config::StateManagement::Service => {
                // Module shares service-level state
                environment_resolver.generate_state_key(&resolved_env, service_name, "service")
            }
            crate::common::service_config::StateManagement::Shared(shared_id) => {
                // Module shares state with other modules
                environment_resolver.generate_state_key(&resolved_env, &shared_id, "shared")
            }
        };
        
        // Generate backend configuration
        let mut config_items = String::new();
        for (key, value) in &resolved_env.backend.config {
            if key == "key" || key == "key_pattern" {
                config_items.push_str(&format!("    key = \"{}\"\n", state_key));
            } else {
                config_items.push_str(&format!("    {} = \"{}\"\n", key, value));
            }
        }
        
        Ok(format!(r#"# Backend configuration generated by Envie
# State management: {:?}
# State key: {}

terraform {{
  backend "{}" {{
{}
  }}
}}
"#,
            module_config.state_management,
            state_key,
            resolved_env.backend.backend_type,
            config_items
        ))
    }
    
    pub fn generate_tfvars_file(
        &self,
        project_name: &str,
        environment_id: &str,
        module_name: &str,
    ) -> String {
        format!(r#"# Auto-generated by Envie - DO NOT EDIT
# This file is automatically generated and will be overwritten

project_name = "{}"
environment_id = "{}"
module_name = "{}"

# Common tags
tags = {{
  Project     = "{}"
  Environment = "{}"
  Module      = "{}"
  ManagedBy   = "envie"
}}
"#, project_name, environment_id, module_name, project_name, environment_id, module_name)
    }

    pub fn write_generated_files(
        &self,
        module_path: &Path,
        dependencies: &[crate::common::service_config::DependencyReference],
        module_config: &ModuleConfig,
        environment_resolver: &EnvironmentResolver,
        environment_overrides: &std::collections::HashMap<String, String>,
        service_name: &str,
        module_name: &str,
        project_name: &str,
        environment_id: &str,
    ) -> Result<()> {
        // Generate backend configuration based on state management strategy
        let backend_content = self.generate_backend_configuration(
            module_config,
            environment_resolver,
            service_name,
            module_name,
        )?;
        
        // Generate and write remote state data sources
        let remote_state_content = self.generate_remote_state_data_sources(
            module_path,
            dependencies,
            environment_resolver,
            environment_overrides,
            service_name,
            module_name,
        )?;
        
        // Generate tfvars file
        let tfvars_content = self.generate_tfvars_file(project_name, environment_id, module_name);
        
        // Write backend configuration file
        let backend_file = module_path.join(".envie-backend.tf");
        std::fs::write(backend_file, backend_content)?;
        
        // Write remote state data sources file
        let remote_state_file = module_path.join(".envie-remote-state.tf");
        std::fs::write(remote_state_file, remote_state_content)?;
        
        // Write tfvars file
        let tfvars_file = module_path.join("terraform.tfvars");
        std::fs::write(tfvars_file, tfvars_content)?;
        
        Ok(())
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;
    use std::fs;

    #[test]
    fn test_remote_state_generation() {
        let generator = TerraformGenerator::new();
        let temp_dir = TempDir::new().unwrap();
        let module_path = temp_dir.path();
        
        let remote_states = vec![
            RemoteStateReference {
                name: "database".to_string(),
                source: "../database/modules/dynamodb".to_string(),
                workspace: Some("sandbox".to_string()),
                outputs: vec!["table_name".to_string(), "table_arn".to_string()],
            }
        ];
        
        let workspace_resolver = WorkspaceResolver::new(
            "myapp-123".to_string(),
            ServiceRegistry {
                services: HashMap::new(),
                modules: HashMap::new(),
            }
        );
        
        let generated = generator.generate_remote_state_data_sources(
            module_path,
            &remote_states,
            &workspace_resolver,
        ).unwrap();
        
        assert!(generated.contains("data \"terraform_remote_state\" \"database\""));
        assert!(generated.contains("workspace = \"sandbox\""));
        assert!(generated.contains("key = \"database/modules/dynamodb/terraform.tfstate\""));
    }
    
    #[test]
    fn test_module_variables_generation() {
        let generator = TerraformGenerator::new();
        
        let mut variables = HashMap::new();
        variables.insert("runtime".to_string(), serde_json::Value::String("nodejs18.x".to_string()));
        variables.insert("timeout".to_string(), serde_json::Value::Number(serde_json::Number::from(30)));
        variables.insert("memory".to_string(), serde_json::Value::Number(serde_json::Number::from(512)));
        
        let module_config = ModuleConfig {
            name: "lambda".to_string(),
            description: "Lambda function".to_string(),
            path: "modules/lambda".to_string(),
            depends: vec![],
            remote_states: vec![],
            variables,
        };
        
        let generated = generator.generate_module_variables(&module_config).unwrap();
        
        assert!(generated.contains("variable \"runtime\""));
        assert!(generated.contains("default = \"nodejs18.x\""));
        assert!(generated.contains("variable \"timeout\""));
        assert!(generated.contains("default = 30"));
    }
}
